// user
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const EDIT_USER = 'EDIT_USER'
export const SHOW_AUTH_DIALOG = 'SHOW_AUTH_DIALOG'

// stats
export const LOAD_STATS_PAGE = 'LOAD_STATS_PAGE'
export const STATS_TRAFIC_SPLIT = 'STATS_TRAFIC_SPLIT'

// projects
export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const RENAME_PROJECT = 'RENAME_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'
export const LOAD_MEMBERS = 'LOAD_MEMBERS'
export const REMOVE_MEMBER = 'REMOVE_MEMBER'
export const CANCEL_INVITE = 'CANCEL_INVITE'

// page groups
export const LOAD_PAGEGROUPS = 'LOAD_PAGEGROUPS'
export const EMPTY_PAGEGROUPS = 'EMPTY_PAGEGROUPS'
export const CREATE_PAGEGROUP = 'CREATE_PAGEGROUP'
export const REMOVE_PAGEGROUP = 'REMOVE_PAGEGROUP'
export const RENAME_PAGEGROUP = 'RENAME_PAGEGROUP'
export const SET_EDITING_PAGEGROUP = 'SET_EDITING_PAGEGROUP'
export const SET_CURRENT_PAGEGROUP = 'SET_CURRENT_PAGEGROUP'

// pages
export const LOAD_PAGES = 'LOAD_PAGES'
export const EMPTY_PAGES = 'EMPTY_PAGES'
export const CREATE_PAGE = 'CREATE_PAGE'
export const RENAME_PAGE = 'RENAME_PAGE'
export const REMOVE_PAGE = 'REMOVE_PAGE'
export const DUPLICATE_PAGE = 'DUPLICATE_PAGE'
export const MOVE_PAGE = 'MOVE_PAGE'

// ui - message box
export const WARNING = 'WARNING'
export const CONFIRM = 'CONFIRM'
export const GET_INPUT = 'GET_INPUT'
export const CLOSE_MESSAGE_BOX = 'CLOSE_MESSAGE_BOX'
export const NEXT_MESSAGE = 'NEXT_MESSAGE'

// ui - image library
export const GET_IMAGE = 'GET_IMAGE'
export const CLOSE_IMAGE_LIBRARY = 'CLOSE_IMAGE_LIBRARY'
export const LOAD_IMAGES = 'LOAD_IMAGES'

// export const NOTICE = 'NOTICE'

// ui - loading
export const LOADING = 'LOADING'
export const LOAD_FAILED = 'LOAD_FAILED'
export const LOAD_DONE = 'LOAD_DONE'

// editor
export const LOAD_PAGE = 'LOAD_PAGE'
export const LOAD_VARIATION = 'LOAD_VARIATION'
export const SAVE_VARIATION = 'SAVE_VARIATION'
export const CREATE_VARIATION = 'CREATE_VARIATION'
export const REMOVE_VARIATION = 'REMOVE_VARIATION'
export const RENAME_VARIATION = 'RENAME_VARIATION'
export const TRAFIC_SPLIT = 'TRAFIC_SPLIT'

export const SAVE_SETTINGS = 'SAVE_SETTINGS'
export const SAVE_CONTENT_STATE = 'SAVE_CONTENT_STATE'
export const UNDO = 'UNDO'
export const REDO = 'REDO'
export const SWITCH_VERSION = 'SWITCH_VERSION'
export const SET_COLOR_SET = 'SET_COLOR_SET'

export const ADD_SECTION = 'ADD_SECTION'
export const MOVE_SECTION = 'MOVE_SECTION'
export const REMOVE_SECTION = 'REMOVE_SECTION'
export const MODIFY_SECTION = 'MODIFY_SECTION'
export const SET_ACTIVE_SECTION_ID = 'SET_ACTIVE_SECTION_ID'
export const SET_CURRENT_SECTION_ID = 'SET_CURRENT_SECTION_ID'

export const SET_ACTIVE_ELEMENT_ID = 'SET_ACTIVE_ELEMENT_ID'
export const MODIFY_ELEMENT = 'MODIFY_ELEMENT'
export const REPLACE_ELEMENT = 'REPLACE_ELEMENT'
export const ADD_ELEMENT = 'ADD_ELEMENT'
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT'
export const REMOVE_ELEMENT_FROM_SECTION = 'REMOVE_ELEMENT_FROM_SECTION'
export const MOVE_ELEMENT = 'MOVE_ELEMENT'
export const MOVE_ELEMENTS = 'MOVE_ELEMENTS'
export const DUPULICATE_ELEMENT = 'DUPULICATE_ELEMENT'

export const ALIGN_UPDATE = 'ALIGN_UPDATE'
export const ALIGN_CLEAR = 'ALIGN_CLEAR'
export const MULTI_SELECT_UPDATE = 'MULTI_SELECT_UPDATE'
export const MULTI_SELECT_DONE = 'MULTI_SELECT_DONE'
export const MULTI_SELECT_CLEAR = 'MULTI_SELECT_CLEAR'
export const UPDATE_MULTI_MOVE = 'UPDATE_MULTI_MOVE'
